// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZCL3sIqJixoU-8Er6d0NKUKuHi4ycLRc',
    appId: '1:662084476071:web:253038003e83febf770f82',
    messagingSenderId: '662084476071',
    projectId: 'todos-4f767',
    authDomain: 'todos-4f767.firebaseapp.com',
    storageBucket: 'todos-4f767.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzAdHSIr4DU8SJU286VoOnHmih7MB41Go',
    appId: '1:662084476071:android:af9fdba8c759e42f770f82',
    messagingSenderId: '662084476071',
    projectId: 'todos-4f767',
    storageBucket: 'todos-4f767.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcukb9UZY_rZ7NWZIXCsD8Jl8hBNi8vBQ',
    appId: '1:662084476071:ios:6a11d4adf5b60a4a770f82',
    messagingSenderId: '662084476071',
    projectId: 'todos-4f767',
    storageBucket: 'todos-4f767.appspot.com',
    iosClientId: '662084476071-tv6f29mechfrnfbgr3i29tvcod6ncuam.apps.googleusercontent.com',
    iosBundleId: 'com.example.verygoodcore.dev',
  );
}
